ARCHQA-179 AttributeError: 'ContextSuite' object has no attribute 'id' When issue in test generator, id() was called on ContextSuite (which has to id method)
git-svn-id: https://nosexunit.svn.sourceforge.net/svnroot/nosexunit/trunk@59 549516f5-ea2c-0410-bc29-f7564ae968c0